version: '3.5'
services:
  api1: # API - Instância 01
    image: lindaines/rinha-backend
    restart: always
    hostname: api1
    depends_on:
      - mysql
    expose:
      - 3000
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
    container_name: api-1

  api2: # API - Instância 01
    image: lindaines/rinha-backend
    hostname: api2
    depends_on:
      - mysql
    expose:
      - 3000
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
    container_name: api-2

  nginx: # Load Balancer
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  db: # Banco de dados
   image: mysql
   deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'